<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classmodule extends \Application\Entity\Classmodule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'pkClassmoduleid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'cwkweight', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'exweight', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'isProject', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'isPrerequisitefor', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'scheme', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'isCore', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkClassid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkModuleid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkAcademicperiod', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'parentmodule');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'pkClassmoduleid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'cwkweight', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'exweight', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'isProject', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'isPrerequisitefor', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'scheme', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'isCore', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkClassid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkModuleid', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'fkAcademicperiod', '' . "\0" . 'Application\\Entity\\Classmodule' . "\0" . 'parentmodule');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Classmodule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPkClassmoduleid()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPkClassmoduleid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPkClassmoduleid', array());

        return parent::getPkClassmoduleid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCwkweight($cwkweight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCwkweight', array($cwkweight));

        return parent::setCwkweight($cwkweight);
    }

    /**
     * {@inheritDoc}
     */
    public function getCwkweight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCwkweight', array());

        return parent::getCwkweight();
    }

    /**
     * {@inheritDoc}
     */
    public function setExweight($exweight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExweight', array($exweight));

        return parent::setExweight($exweight);
    }

    /**
     * {@inheritDoc}
     */
    public function getExweight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExweight', array());

        return parent::getExweight();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsProject($isProject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsProject', array($isProject));

        return parent::setIsProject($isProject);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsProject', array());

        return parent::getIsProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPrerequisitefor($isPrerequisitefor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPrerequisitefor', array($isPrerequisitefor));

        return parent::setIsPrerequisitefor($isPrerequisitefor);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPrerequisitefor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPrerequisitefor', array());

        return parent::getIsPrerequisitefor();
    }

    /**
     * {@inheritDoc}
     */
    public function setScheme($scheme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScheme', array($scheme));

        return parent::setScheme($scheme);
    }

    /**
     * {@inheritDoc}
     */
    public function getScheme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScheme', array());

        return parent::getScheme();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCore($isCore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCore', array($isCore));

        return parent::setIsCore($isCore);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCore', array());

        return parent::getIsCore();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkClassid(\Application\Entity\Classes $fkClassid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkClassid', array($fkClassid));

        return parent::setFkClassid($fkClassid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkClassid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkClassid', array());

        return parent::getFkClassid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkModuleid(\Application\Entity\Module $fkModuleid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkModuleid', array($fkModuleid));

        return parent::setFkModuleid($fkModuleid);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkModuleid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkModuleid', array());

        return parent::getFkModuleid();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAcademicperiod(\Application\Entity\Academicyear $fkAcademicperiod = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAcademicperiod', array($fkAcademicperiod));

        return parent::setFkAcademicperiod($fkAcademicperiod);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAcademicperiod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAcademicperiod', array());

        return parent::getFkAcademicperiod();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentmodule(\Application\Entity\Classmodule $parentmodule = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentmodule', array($parentmodule));

        return parent::setParentmodule($parentmodule);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentmodule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentmodule', array());

        return parent::getParentmodule();
    }

}
