<div class="row">
<div class="col col-md-1">
    &nbsp;
    </div>
        <div class="col col-md-10">
            <div class="panel panel-default">
                <h3 class="page-header"><?php echo sprintf("%s %s %s",$period->getParentid()->getAcyr(),"semester",$period->getAcyr()); ?> - Modules</h3>
            <div class="panel-body">
            <hr>
            
            
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Description</th>
        <th>type</th>
        <th>Weighting(%)</th>
        <th>Date created</th>
        <th width="170">Grades captured(%)</th>
        <th width="90"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($modules as $module){
          //$status = empty($module['allocations'])?"Unassigned":"Testing";
      ?>

      <tr>
          <td></td>
          <td><?php echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td><?php echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td></td>
        <td></td>
        <td align="right"><strong>10%</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><a href="<?php echo $this->url("examination",array("action"=>"assessements")); ?>" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-list"></i></a>&nbsp;<a href="<?php echo $this->url("examination",array("action"=>"assessements")); ?>" class="btn btn-sm btn-success"><i class="glyphicon glyphicon-remove"></i></a>    </td>
      </tr>
      
      <?php
      }
      
      ?>
    </tbody>
</table>
           
            </div>
                </div>
        </div>
</div>
        