<div class="row">
<div class="col col-md-2">
    &nbsp;
    </div>
        <div class="col col-md-8">
            <div class="panel panel-default">
                <h3 class="page-header"><?php //echo sprintf("%s %s %s",$period->getParentid()->getAcyr(),"semester",$period->getAcyr()); ?> - capture marks</h3>
            <div class="panel-body">
                
                &nbsp;<a class="btn btn-sm btn-success pull-right"><i class="glyphicon glyphicon-upload"></i> Import marks </a>&nbsp;<a class="btn btn-sm btn-success"><i class="glyphicon glyphicon-save"></i> Save </a>&nbsp;<a class="btn btn-sm btn-info"><i class="glyphicon glyphicon-remove"></i> Cancel </a>
            <hr>
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Registration #</th>
        <th>Surname</th>
        <th>First name</th>
        <th>Gender</th>
        <th width="100">Mark</th>
      </tr>
    </thead>
    <tbody>
      <?php
      //foreach($modules as $module){
          //$status = empty($module['allocations'])?"Unassigned":"Testing";
      ?>

      <tr>
          <td>BIT/03/PE/0021</td>
          <td>KUMWEMBE<?php //echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td>HUMPHREY<?php //echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td>MALW</td>
        <td><input class="form-control" type="text" /></td>
      </tr>
      <tr>
          <td>BIT/03/PE/0021</td>
          <td>KUMWEMBE<?php //echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td>HUMPHREY<?php //echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td>MALW</td>
        <td><input class="form-control" type="text" /></td>
      </tr>
      <tr>
          <td>BIT/03/PE/0021</td>
          <td>KUMWEMBE<?php //echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td>HUMPHREY<?php //echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td>MALW</td>
        <td><input class="form-control" type="text" /></td>
      </tr>
      <tr>
          <td>BIT/03/PE/0021</td>
          <td>KUMWEMBE<?php //echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td>HUMPHREY<?php //echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td>MALW</td>
        <td><input class="form-control" type="text" /></td>
      </tr>
      <tr>
          <td>BIT/03/PE/0021</td>
          <td>KUMWEMBE<?php //echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td>HUMPHREY<?php //echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td>MALW</td>
        <td><input class="form-control" type="text" /></td>
      </tr>
      <tr>
          <td>BIT/03/PE/0021</td>
          <td>KUMWEMBE<?php //echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td>HUMPHREY<?php //echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td>MALW</td>
        <td><input class="form-control" type="text" /></td>
      </tr>
      <tr>
          <td>BIT/03/PE/0021</td>
          <td>KUMWEMBE<?php //echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td>HUMPHREY<?php //echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td>MALW</td>
        <td><input class="form-control" type="text" /></td>
      </tr>
      <tr>
          <td>BIT/03/PE/0021</td>
          <td>KUMWEMBE<?php //echo sprintf("%s (%s)",$module->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$module->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
        <td>HUMPHREY<?php //echo $module->getFkClassmoduleid()->getFkClassid()->getClassCode(); ?></td>
        <td>MALW</td>
        <td><input class="form-control" type="text" /></td>
      </tr>
      <?php
      //}
      
      ?>
    </tbody>
</table>
       <hr>
       <a class="btn btn-sm btn-success"><i class="glyphicon glyphicon-save"></i> Save </a>&nbsp;<a class="btn btn-sm btn-info"><i class="glyphicon glyphicon-remove"></i> Cancel </a>
            </div>
                </div>
        </div>
</div>
        