<div class="row">
<div class="col col-md-1">
    &nbsp;
    </div>
        <div class="col col-md-10">
            <div class="panel panel-default">
            <h3 class="page-header">2015/2016 - Lecture module allocation</h3>
            <div class="panel-body">
                <hr>
                <div class="alert alert-danger">
                
                <?php //echo $msg; ?>&nbsp;<strong>SERVICING DEPARTMENT</strong>
            </div>
            
            <table class="table table-bordered table-striped table-hover">
                <thead>
                  <tr>
                    <th>Class</th>
                    <th>Module</th>
                    <th>Department</th>
                    <th>Lecturer</th>
                    <th width="50"></th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  //foreach($faculties as $faculty){
                  ?>

                  <tr>
                    <td>Mathematics(MAT-200)</td>
                    <td>Thengolose P(MTS)</td>
                    <td>Mathematics(MAT-200)</td>
                    <td>Thengolose P(MTS)</td>
                    <td><a href="#" class="btn btn-success">Allocate</a>    </td>
                  </tr>
                  <tr>
                    <td>Web site development(WEB-200)</td>
                    <td>Unassigned</td>
                    <td>Mathematics(MAT-200)</td>
                    <td>Thengolose P(MTS)</td>
                    <td><a href="#" class="btn btn-danger">Allocate</a>    </td>
                  </tr>
                  <?php
                 // }

                  ?>
                </tbody>
            </table>
            <hr>
             <?php
            for($counter = 1; $counter<=3; $counter++){
            ?>
            <div class="alert alert-info">
                
                <?php //echo $msg; ?>&nbsp;<strong>Bachelor of science in information technology year 1(BIT1)</strong>
            </div>
            
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Module</th>
        <th>Lecturer</th>
        <th width="50"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      //foreach($faculties as $faculty){
      ?>

      <tr>
        <td>Mathematics(MAT-200)</td>
        <td>Thengolose P(MTS)</td>
        
        <td><a href="#" class="btn btn-success">Allocate</a>    </td>
      </tr>
      <tr>
        <td>Web site development(WEB-200)</td>
        <td>Unassigned</td>
        
        <td><a href="#" class="btn btn-danger">Allocate</a>    </td>
      </tr>
      <?php
     // }
      
      ?>
    </tbody>
</table>
            <?php
            }
            ?>
                <div class="col ">
  <form class="form-inline" role="form">
    <div class="form-group">
      <label for="email">Show:</label>

<select class="form-control">
  <option>10</option>
  <option>20</option>
  <option>30</option>
  <option>50</option>
  <option>100</option>
</select> 
       
          
    </div>

      <a class="btn btn-success">Download <i class="glyphicon glyphicon-download"></i></a> 
                 
               </div>
            </div>
                </div>
        </div>
</div>
        