<div class="row">
<div class="col col-md-1">
    &nbsp;
    </div>
        <div class="col col-md-10">
            <div class="panel panel-default">
                <h3 class="page-header"><?php echo sprintf("%s %s %s",$period->getParentid()->getAcyr(),"semester",$period->getAcyr()); ?> - Lecturer module allocation</h3>
            <div class="panel-body">
                <a class="btn btn-info "><i class="glyphicon glyphicon-eye-open"></i> Unassigned </a>&nbsp;<a class="btn btn-warning pull-right"><i class="glyphicon glyphicon-file"></i> Export </a> <br>
                <hr>
                <?php
                if(!empty($servicedmodules)){
                ?>
                <div class="alert alert-danger">
                
                <?php //echo $msg; ?>&nbsp;<strong>SERVICING DEPARTMENTS</strong>
            </div>
            
            <table class="table table-bordered table-striped table-hover">
                <thead>
                  <tr>
                    <th>Class</th>
                    <th>Module</th>
                    <th>Department</th>
                    <th>Lecturer</th>
                    <th width="50"></th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  foreach($servicedmodules as $servicedmodule){
                      if($servicedmodule->getFlag() != "UNABLETOALLOCATE"){
                  ?>

                  <tr>
                    <td><?php echo sprintf("%s (%s)",$servicedmodule->getFkClassmoduleid()->getFkClassid()->getClassName(),$servicedmodule->getFkClassmoduleid()->getFkClassid()->getClassCode()); ?></td>
                    <td><?php echo sprintf("%s (%s)",$servicedmodule->getFkClassmoduleid()->getFkModuleid()->getModuleName(),$servicedmodule->getFkClassmoduleid()->getFkModuleid()->getModuleCode()); ?></td>
                    <td><?php echo $servicedmodule->getReqdept()->getDeptCode(); ?></td>
                    <td><?php echo !empty($servicedmodule->getFklmid())?sprintf("%s, %s",$servicedmodule->getFklmid()->getFkStaffid()->getFkUserid()->getSurname(),substr($servicedmodule->getFklmid()->getFkStaffid()->getFkUserid()->getFirstname(),0,1)):"Not assigned" ?></td>
                  <td><?php if(!empty($servicedmodule->getFklmid())){ ?><a href="<?php echo $this->url("examination",array("action"=>"servicemoduleform","id"=>$servicedmodule->getFkClassmoduleid()->getPkClassmoduleid(),"subparam"=>$servicedmodule->getPkSmid())); ?>" class="btn btn-success">Change</a><?php }else{ ?> <a href="<?php echo $this->url("examination",array("action"=>"servicemoduleform","id"=>$servicedmodule->getFkClassmoduleid()->getPkClassmoduleid(),"subparam"=>$servicedmodule->getPkSmid())); ?>" class="btn btn-danger">Allocate</a><?php } ?>   </td>
                  </tr>
                  
                  <?php
                      }
                  }

                  ?>
                </tbody>
            </table>
            <hr>
             <?php
                }
            foreach($allocations as $allocation){
            ?>
            <div class="alert alert-info">
                
                <?php //echo $msg; ?>&nbsp;<strong><?php echo strtoupper($allocation['CLASSNAME']); ?></strong>
            </div>
            
<table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th>Module</th>
        <th>Lecturer</th>
        <th width="50"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($allocation['MODULE'] as $module){
          //$status = empty($module['allocations'])?"Unassigned":"Testing";
      ?>

      <tr>
          <td><?php echo sprintf("%s (%s)",$module['module']->getFkModuleid()->getModuleName(),$module['module']->getFkModuleid()->getModuleCode()); ?></td>
        <td><?php echo $module['allocations']; ?></td>
        
        <td><?php if($module['isinhand']){ if($module['canmodify']){ ?><a href="<?php echo $this->url("examination",array("action"=>"lcform","id"=>$module['module']->getPkClassmoduleid(),"subparam"=>$module['staff']->getPkLmid())); ?>" class="btn btn-success">Change</a> <?php }else{ ?> <a href="<?php echo $this->url("examination",array("action"=>"lcform","id"=>$module['module']->getPkClassmoduleid())); ?>" class="btn btn-danger">Allocate</a> <?php } } ?>   </td>
      </tr>
      
      <?php
      }
      
      ?>
    </tbody>
</table>
            <?php
            }
            ?>
               
            </div>
                </div>
        </div>
</div>
        